### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by philsinatra** [hmh84/idm231-hmh84#1]
Consider reorganizing your folder structure so that source code files for the web app are separated from documentation and resources. For help with this, ask for me to review at the beginning of class.

Adding your .xd files is fine if you want to track them in the repo, but if you want quick feedback and to be able to go through your design concepts, .png and .jpg files will work better since they can be viewed directly on GitHub without having to download and run external software.

Consider adding a .gitignore file so you can control what is left out of the repository but still included in your local project folder. 

- [macOS example](https://github.com/github/gitignore/blob/master/Global/macOS.gitignore)
- [Windows example](https://github.com/github/gitignore/blob/master/Global/Windows.gitignore)

**Comment by hmh84** [comment]
I have restructured the folder and added a GitIgnore file.
However, I am not seeing my recent commits on GitHub web (.com)
Any thoughts?

**Comment by philsinatra** [comment]
| I am not seeing recent commits to my repo on GitHub web (.com)

I see commits as recent as today:

[https://github.com/hmh84/idm231-hmh84/commits/master](https://github.com/hmh84/idm231-hmh84/commits/master)

| Now that I have restructured, the link to my zodiac site now requires /app -Is this how it should act? And would you like me to resubmit the link in BB: Assignment Preparation

No you should not need to change the URL. The reorganization happens only on your computer, the files on the live server don't have to move. I can review your setup with you in lab next class. I'm also on campus Wednesday's for a 6pm class if you want to swing by for a few minutes before then.

**Comment by hmh84** [comment]
The commits you are seeing are likely just me deleting the .DS_Store files which were done on GitHub Web.

Here's a screenshot with GitHub Desktop and Web side by side.
[](https://drive.google.com/file/d/1shIfPF7dNjcEFV-zJr51y0RbMin9xwr7/view?usp=sharing)

**Comment by philsinatra** [comment]
Are your commits all local and not _pushed_ to the remote repository? Look for the push/publish button or a message reminding you to push your local changes.

![Screen Shot 2020-01-14 at 4 27 06 PM](https://user-images.githubusercontent.com/1465808/72384082-c135d800-36ea-11ea-88a2-441fe2d91b83.png)

**Comment by hmh84** [comment]
There was a marge issue with GitHub Desktop's pull request. Had to sort out the DS_Store deletions, then I was able to push all my local commits. Could have been prevented if I just had a .gitignore in the first place.. dohh 🤦‍♂ 

I will ask you about the url concern next class, otherwise no issues 👍
